$('#form').alpaca({

    // These files will pre-load form with data BUT
    // here it is done with Alpaca's widget data pre-load
    // "schemaSource": "./serialization-schema.json",
    // "dataSource": "./serialization-data.json",

   // This is the only code I had to "write" (copied from Alpaca site)
   "postRender": function(form) {
        // Serialize is the submit button element
        $("#serialize").click(function() {
        var formData = form.getValue();

        // Send the data to the server via HTML POST
        $.ajax({
            type: "POST",
            url: "person/create",  // url: "cemetery/create",
            data: {json:JSON.stringify(formData)},
            // Render response from server in alert box
            success: function(data, msg, xhr) {
              alert(msg);
            }
          });
        // DEBUG: This is data we sent out
        // alert(JSON.stringify(formData));
        });
    },


    // All of this was generated by Alpaca
    // $('#div').alpaca({
    "schema": {
        "type": "object",
        "required": false,
        "properties": {
            "id": {
                "type": "string",
                "required": false
            },
            "birthName": {
                "type": "string",
                "required": false
            },
            "deathName": {
                "type": "string",
                "required": false
            },
            "birthDate": {
                "type": "string",
                "required": false
            },
            "deathDate": {
                "type": "string",
                "required": false
            },
            "deathAge": {
                "type": "number",
                "required": false
            },
            "findagraveid": {
                "type": "number",
                "required": false
            },
            "markerid": {
                "type": "string",
                "required": false
            },
            "veteranStatus": {
                "type": "boolean",
                "required": false,
                "readonly": false,
                "enum": [
                    "Revolution",
                    "War of 1812",
                    "Spanish-American",
                    "WWI",
                    "WWII",
                    "Korea",
                    "Vietnam",
                    "Iraq"
                ]
            },
/*            "inRevolution": {
                "type": "boolean",
                "required": false
            },
            "inEighteenTwelve": {
                "type": "boolean",
                "required": false
            },
            "inSpanAmer": {
                "type": "boolean",
                "required": false
            },
            "inWWI": {
                "type": "boolean",
                "required": false
            },
            "inWWII": {
                "type": "boolean",
                "required": false
            },
            "inKorea": {
                "type": "boolean",
                "required": false
            },
            "inVietnam": {
                "type": "boolean",
                "required": false
            },
            "inIraq": {
                "type": "boolean",
                "required": false
            },*/
            "isFamous": {
                "type": "boolean",
                "required": false
            }
        }
    },
    "options": {
        "focus": false,
        "type": "object",
        "validate": true,
        "disabled": false,
        "showMessages": true,
        "collapsible": true,
        "legendStyle": "button",
        "form":{
            "buttons":{
               "submit": {
                  "click":function(e){
                    var formData = this.getValue();
                    // Send the data to the server via HTML POST
                    $.ajax({
                      type: "POST",
                      url: "person/create", // url: "cemetery/create",
                      data: {json:JSON.stringify(formData)},
                      // Render response from server in alert box
                      success: function(data, msg, xhr) {
                        alert(msg);
                        } // success
                     }); // ajax
                   // this.clear(true);
                   } // click
                 }, // submit
                "reset": {}
              } // buttons
           },

        "fields": {
            "id": {
                "type": "text",
                "validate": true,
                "showMessages": true,
                "disabled": false,
                "hidden": true,
                "label": "id",
                "hideInitValidationError": false,
                "focus": true,
                "size": 40,
                "typeahead": {},
                "allowOptionalEmpty": false
            },
            "birthName": {
                "type": "text",
                "validate": true,
                "showMessages": true,
                "disabled": false,
                "hidden": false,
                "label": "Birth Name",
                "hideInitValidationError": false,
                "focus": true,
                "size": 40,
                "typeahead": {},
                "allowOptionalEmpty": false
            },
            "deathName": {
                "type": "text",
                "validate": true,
                "showMessages": true,
                "disabled": false,
                "hidden": false,
                "label": "Name at Death",
                "helper": "e.g. married name (can be the same as Birth Name)",
                "hideInitValidationError": false,
                "focus": true,
                "size": 40,
                "typeahead": {},
                "allowOptionalEmpty": false
            },
            "birthDate": {
                "type": "date",
                "validate": true,
                "showMessages": true,
                "disabled": false,
                "hidden": false,
                "label": "Birth Date",
                "hideInitValidationError": false,
                "focus": true,
                "size": 40,
//                "typeahead": {},
//                "allowOptionalEmpty": false,
//                "dateFormat": "MM/DD/YYYY",
//                "picker": "[object Object]"
            },
            "deathDate": {
                "type": "date",
                "validate": true,
                "showMessages": true,
                "disabled": false,
                "hidden": false,
                "label": "Death Date",
                "hideInitValidationError": false,
                "focus": true,
                "size": 40,
//                "typeahead": {},
//                "allowOptionalEmpty": false,
//                "dateFormat": "MM/DD/YYYY",
//                "picker": "[object Object]"
            },
            "deathAge": {
                "type": "number",
                "validate": true,
                "showMessages": true,
                "disabled": false,
                "hidden": false,
                "label": "Age at Death",
                "hideInitValidationError": false,
                "focus": true,
                "size": 40,
                "typeahead": {},
                "allowOptionalEmpty": false
            },
            "findagraveid": {
                "type": "number",
                "validate": true,
                "showMessages": true,
                "disabled": false,
                "hidden": false,
                "label": "Find A Grave Memorial #",
                "hideInitValidationError": false,
                "focus": true,
                "size": 40,
                "typeahead": {},
                "allowOptionalEmpty": false
            },
            "markerid": {
                "type": "text",
                "validate": true,
                "showMessages": true,
                "disabled": false,
                "hidden": true,
                "label": "marker_id",
                "hideInitValidationError": false,
                "focus": true,
                "size": 40,
                "typeahead": {},
                "allowOptionalEmpty": false
            },
            "veteranStatus": {
                "type": "checkbox",
                "validate": true,
                "showMessages": true,
                "disabled": false,
                //"hidden": false,
                "label": "Veteran Status",
                //"hideInitValidationError": false,
                "focus": true,
                //"allowOptionalEmpty": false,
                //"removeDefaultNone": false,
                "multiple": true,
                "readonly": false,
                "rightLabel": "",
                "optionLabels": [ 
                    "Revolution",
                    "War of 1812",
                    "Spanish-American",
                    "WWI",
                    "WWII",
                    "Korea",
                    "Vietnam",
                    "Iraq"
                ]           
            },
/*            "inRevolution": {
                "type": "checkbox",
                "label": "Revolution",
                "validate": true,
                "disabled": false,
                "showMessages": true,
                "rightLabel": ""
            },
            "inEighteenTwelve": {
                "type": "checkbox",
                "label": "War of 1812",
                "validate": true,
                "disabled": false,
                "showMessages": true,
                "rightLabel": ""
            },
            "inSpanAmer": {
                "type": "checkbox",
                "label": "Spanish-American",
                "validate": true,
                "disabled": false,
                "showMessages": true,
                "rightLabel": ""
            },
            "inWWI": {
                "type": "checkbox",
                "label": "World War I",
                "validate": true,
                "disabled": false,
                "showMessages": true,
                "rightLabel": ""
            },
            "inWWII": {
                "type": "checkbox",
                "label": "World War II",
                "validate": true,
                "disabled": false,
                "showMessages": true,
                "rightLabel": ""
            },
            "inKorea": {
                "type": "checkbox",
                "label": "Korea",
                "validate": true,
                "disabled": false,
                "showMessages": true,
                "rightLabel": ""
            },
            "inVietnam": {
                "type": "checkbox",
                "label": "Vietnam",
                "validate": true,
                "disabled": false,
                "showMessages": true,
                "rightLabel": ""
            },
            "inIraq": {
                "type": "checkbox",
                "label": "Iraq",
                "validate": true,
                "disabled": false,
                "showMessages": true,
                "rightLabel": ""
            },*/
            "isFamous": {
                "type": "checkbox",
                "label": "isFamous",
                "validate": true,
                "disabled": false,
                "showMessages": true,
                "rightLabel": ""
            }
        }
    },
    "data": {}
});
